kind: Service
apiVersion: v1
metadata: 
  name: myservice
  labels:
    app: myspringbootaap
spec:
  selector:
    app: myspringbootaap
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9099
    nodePort: 30034
 
