kind: Service
apiVersion: v1
metadata: 
  name: myservice
  labels:
    app: myspringbootaap
spec:
  selector:
    app: myspringbootaap
  type: NodePort
  ports:
  - nodePort: 30036
    port: 9099
     targetPort: 9099
 
